### PR TITLE
Fix for issue #201 with editing todo tasks

### PR DESCRIPTION
**Pull request by landegt**
Fix to issue #201 

Simple fix to the issue by replacing the return value Clutter.EVENT_STOP with Clutter.EVENT_PROPAGATE as recommended here [https://gitlab.gnome.org/GNOME/mutter/-/issues/2086](url)

Tested on Pop!_OS 22.04 LTS

### CODE REVIEW

**Comment by rcsm17** [comment]
How can I apply this fix ?

**Comment by c-git** [comment]
If you look at the [files](https://github.com/zagortenay333/timepp/pull/208/files) tab you can see which files would be changed by this PR. That should show you what to change.

**Comment by zagortenay333** [comment]
I won't be merging this. I'm currently working on a relatively big upgrade to the extension: fixing bugs, adding some features and porting it to typescript... This fix will be included in that upgrade.

**Comment by babakslt** [comment]
@landegt Thanks it fixed the problem.

**Pull request closed without merging**
