### PR TITLE
support gnome-shell 3.34

### LINKED ISSUE #113: Unsupported gnome 3.34
watch out for the shell theme adjustments on this update

Here's the JournalCtl output that I thought that was relevant. 
https://gist.github.com/Lord-Guckavin/4b60d3e2f652d08a276b4c402f93ea30

### PR DESCRIPTION
**Pull request by karneds**
fix #113

### CODE REVIEW

**Comment by zagortenay333** [comment]
Ah, that's all? It works on 3.34 now?

**Comment by karneds** [comment]
Yep. It works 
it works

**Comment by zagortenay333** [comment]
Ok, I got a hold of gnome 3.34.

You broke the timer... You changed the the signal from 'value-changed' to 'notify::value' without updating the signal handler signature.

The new handler takes no params now, so pass the slider manually:

```
this.sigm.connect(this.slider, 'notify::value', () => this.slider_changed(this.slider.value));
```

Also here to make sure the fullscreen slider works:
```
this.slider.connect('notify::value', () => {
        this.delegate.slider_changed(this.slider.value);
```
```
    slider_changed (value) {
        if (this.tic_mainloop_id) {
            Mainloop.source_remove(this.tic_mainloop_id);
            this.tic_mainloop_id = null;
        }
```

**Comment by zagortenay333** [comment]
I'm not sure why you reference issue #112. That one is about gnome-shell 3.28.

**Comment by karneds** [comment]
> You broke the timer..

Sorry) I didn't see any errors in log and don`t check up timer,   because not not use it
Fixed it

**Comment by zagortenay333** [comment]
Thx. Btw, Is this compatible with 3.32 btw? I'll probably make a branch for it otherwise.

**Comment by diguabo** [comment]
Great extension. Thanks!

Tried codes on master branch. It doesn't work on my Ubuntu 19.10 with gnome shell 3.34 though.

**Comment by zagortenay333** [comment]
Thx. It's merged now.

@diguabo Try again, I hadn't merged this pull request yet.

**Comment by diguabo** [comment]
> Thx. It's merged now.
> 
> @diguabo Try again, I hadn't merged this pull request yet.

works fine now. :)

Thanks!

P.S.
Please update the extension on https://extensions.gnome.org/, so others might appreciate.

**Comment by zagortenay333** [comment]
I did, but it'll take a while to get reviewed.

**Pull request merged**
