### PR TITLE
gnome 42 compatibility

### PR DESCRIPTION
**Pull request by digitalillusion**
- fix fullscreen modal not closing
- fix preferences titlebar error
- declare shell version 42 support in metadata

### CODE REVIEW

**Comment by DanRioDev** [comment]
@zagortenay333 we need G42 compat :pray:

**Comment by digitalillusion** [comment]
@zagortenay333 I've finally fixed the freeze happening at midnight. I'm no longer aware of any other stability issues, but if you are, I can investigate. I think this PR is worth merging

**Comment by zagortenay333** [comment]
@digitalillusion Thanks a lot! The only thing that would need to be done is determine whether this version runs on version 40 and 41. If not, then those version have to be removed from the metadata file.

**Comment by digitalillusion** [comment]
I took the time to test the code in gnome 40 and 41. Indeed the fullscreen modal api change is not backward compatible so I removed those version from metadata file

**Comment by c-git** [comment]
> I took the time to test the code in gnome 40 and 41. Indeed the fullscreen modal api change is not backward compatible so I removed those version from metadata file

@digitalillusion thanks for testing I haven't had a chance to do it yet.

**Pull request merged**
