### PR TITLE
due selector for kanban view

### PR DESCRIPTION
**Pull request by mbroedl**
Using /^\s*(?:due|DUE)([<=>]+)(\d+)([dwmy])$/
So e.g. due<2w or due>=1d or due=0d will be parsed and can be filtered.
Suggested changes:
- add task.due_in_days and a split off function of date_delta_str in misc_utils
- add filter function and amend to filters

NOTE: since < and > were parsed to HTML special characters, there are some
workarounds necessary.
NOTE2: It may be reasonable to move the match_due_date function from
view__default to somewhere else. Did not know where would be most feasible,
so I'm happy about ideas on that.

### CODE REVIEW

**Comment by mbroedl** [comment]
What it looks like now:
image

**Comment by zagortenay333** [comment]
Thx for the pull. 

I only don't like the way you added that `due_in_days` to the task item. This should be done either by:

* adding that property and then adding a method like `check_due_date` (similar to `check_recurrence`) to the task item that would update the tasks `due_in_days` prop.  
Then the `_check_dates` function from MAIN would need to be updated to refresh this prop for every task at the beginning of a new day. Also the `reset` method would need to be updated in the `if (self_update)` conditional.
I think this is overkill since this prop isn't needed anywhere else.

* or the much simpler way by not adding anything to the task_item and just letting view__default calculate this prop on the fly as it's trying to figure out whether to put the task in. So the `match_due_date` func should do this.

You must hook the view__default up to the `new-day` signal so that it updates the kanban columns at the start of a new day.

It would be nice if you updated the readme instructions. I can't quite figure out the syntax from regex.

**Comment by mbroedl** [comment]
Thanks for your quick reply!
I had thought about having `match_due_date` calculate everything; but then I thought that if it was called for every task with a due date it would be quite a lot of excess memory usage? I suppose that's why I exclude conditions from the beginning on...

Are you happy to keep `match_due_date` where it is or shall I move it to e.g. misc_utils or a function outside that class?

The regex in `kan:` would be
- due or DUE
- <= or >= or > or < or =  or == (or any other combination of these, but they cause the default)
- a non-negative number
- d(ays), w(eeks), m(onths), y(ears) (1 week = 7 days, 1 month = 30 days, 1 year = 365 days)
- so `due<=1w` is equal to `due<=7d` which includes all tasks that are due before or on 7 days from today
- other examples: `due=0d` (today), `due<=1d` (before and including tomorrow), `due>1m` (due more than 30 days from now)

But I will make sure to make it a bit nicer in the readme.
Going to sort your comments out in the next few days! Thanks again!

**Comment by zagortenay333** [comment]
It's fine to keep `match_due_date` where it is; no reason to abstract it out if it's used in one place only.

The reason I'm not sure about this pull request is because of drag-and-drop.

I also thought about adding a kanban column for due dates, but I couldn't come up with a behavior for dnd. I haven't tested your pull yet, so I don't know how you intend to deal with that.

**Comment by mbroedl** [comment]
Argh, I didn't think about dnd yet. It seems to behave fine (sticks where it should stick, removes projects/contexts or adds them back in). The only thing that does not work is persistence of moving something to the due date column (or away from it if it's before the column a task should be moved to). Because obviously no due date is added or removed yet.

Re: adding due dates, one could add a due date equal to the maximum span? Or ask? Or infer it (roughly) from the position in the column and the other due dates in there (assuming sorted by due date)?

Other possible errors would be when e.g. `kan:due<5d|due<3d` which would leave the second column empty (but I think that's alright because the same happens with other items in more columns)

**Comment by zagortenay333** [comment]
I thought about this. The best thing to do is to just prevent the user from dragging tasks in/out of a due date column.

**Comment by bluebirch** [comment]
Was this implemented in master? I can't seem to make the syntax work.

**Comment by zagortenay333** [comment]
No. It was closed due to inactivity.

**Pull request closed without merging**
