### PR TITLE
Use of ES6 classes - icons not working

### PR DESCRIPTION
**Pull request by mirko-laruina**
With the GNOME update to 3.32, which requires pure ES6 classes, this extension stopped working.
I've tried fixing it, now it works but all the icons are missing.
I had to comment out all the instructions which used the signal `custom-css-changed` because, otherwise, GNOME would throw an error about it not existing in `Gjs_Timepp` and I think this is strictly related.
I have no idea what to do next so I'm sharing my changes, hoping they could be useful.

### CODE REVIEW

**Comment by zagortenay333** [comment]
I'm currently not using 3.32 and I'm also working on a much better replacement for timepp as well as the todo.txt format, since I don't like being forced to use gnome-shell for my todos and the todo.txt format frankly sucks..

So you're either gonna have to make it work completely or timepp isn't getting ported to 3.32 any time soon I'm afraid.

**Comment by mirko-laruina** [comment]
Okay, working!
Currently testing, but all should be fine.
I've removed some warnings too ( ByteArray.toString() ones).
The icons were not working because, for whatever reason, using the search part gives problem (Caffeine has the same problem and I suspect many more).

**Comment by zagortenay333** [comment]
Nice work! Thx for doing this. Let me know when you think it's ready to be merged.

**Comment by mirko-laruina** [comment]
Thank you for your awesome extensions!
Seen the feedbacks on issue #97, I think it is ready.

**Comment by zagortenay333** [comment]
Btw, how do we stand witth backward compatibility here? Is it now only working on 3.32?

**Comment by mirko-laruina** [comment]
Oh, forgot about that.
From what I've read, it could break the extensions for all the previous versions of GNOME, but I have no idea if it is the case

**Comment by zagortenay333** [comment]
Merged. Thx for the work! :+1:

**Pull request merged**
